name: Build and upload an artifact

on: push

env:
  ARTIFACT_NAME: hello

jobs:

  build-and-upload:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
   
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build ${{ ARTIFACT_NAME }}.go

    - name: Test
      run: source ./${{ ARTIFACT_NAME }}
    
    - name: Upload a Build Artifact ${{ ARTIFACT_NAME }}
      uses: actions/upload-artifact@v3.1.1
      with:
        name: linux
        path: ./${{ ARTIFACT_NAME }}
